builds:
- ldflags:
    - -s -w -X github.com/spinnaker/kleat/pkg/version.Version={{.Version}} -X github.com/spinnaker/kleat/pkg/version.Commit={{.Commit}} -X github.com/spinnaker/kleat/pkg/version.Date={{.Date}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm64
