// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appengine_provider.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Google App Engine (GAE) provider.
type AppengineProvider struct {
	// Whether the provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured accounts.
	Accounts []*AppengineAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// The name of the primary account.
	PrimaryAccount       string   `protobuf:"bytes,3,opt,name=primaryAccount,proto3" json:"primaryAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppengineProvider) Reset()         { *m = AppengineProvider{} }
func (m *AppengineProvider) String() string { return proto.CompactTextString(m) }
func (*AppengineProvider) ProtoMessage()    {}
func (*AppengineProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_b058e5b683ee2a72, []int{0}
}

func (m *AppengineProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppengineProvider.Unmarshal(m, b)
}
func (m *AppengineProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppengineProvider.Marshal(b, m, deterministic)
}
func (m *AppengineProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppengineProvider.Merge(m, src)
}
func (m *AppengineProvider) XXX_Size() int {
	return xxx_messageInfo_AppengineProvider.Size(m)
}
func (m *AppengineProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_AppengineProvider.DiscardUnknown(m)
}

var xxx_messageInfo_AppengineProvider proto.InternalMessageInfo

func (m *AppengineProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *AppengineProvider) GetAccounts() []*AppengineAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *AppengineProvider) GetPrimaryAccount() string {
	if m != nil {
		return m.PrimaryAccount
	}
	return ""
}

// Configuration for an App Engine account.
type AppengineAccount struct {
	// The interval in seconds at which Spinnaker will poll for updates in
	// your App Engine clusters.
	CachingIntervalSeconds int32 `protobuf:"varint,1,opt,name=cachingIntervalSeconds,proto3" json:"cachingIntervalSeconds,omitempty"`
	// The environment name for the account. Many accounts can share the
	// same environment (e.g., dev, test, prod).
	Environment string `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	// The gcloud release track (`ALPHA`, `BETA`, or `STABLE`) that Spinnaker
	// will use when deploying to App Engine.
	GcloudReleaseTrack string `protobuf:"bytes,3,opt,name=gcloudReleaseTrack,proto3" json:"gcloudReleaseTrack,omitempty"`
	// A username to be used when connecting to a remote git repository
	// server over HTTPS. If set, `gitHttpsPassword` must also be set.
	GitHttpsUsername string `protobuf:"bytes,4,opt,name=gitHttpsUsername,proto3" json:"gitHttpsUsername,omitempty"`
	//  A password to be used when connecting to a remote git repository
	//  server over HTTPS. If set, `gitHttpsUsername` must also be set.
	GitHttpsPassword string `protobuf:"bytes,5,opt,name=gitHttpsPassword,proto3" json:"gitHttpsPassword,omitempty"`
	// An OAuth token provided by Github for connecting to a git repository
	// over HTTPS. See
	// https://help.github.com/articles/creating-an-access-token-for-command-line-use
	// for more information.
	GithubOAuthAccessToken string `protobuf:"bytes,6,opt,name=githubOAuthAccessToken,proto3" json:"githubOAuthAccessToken,omitempty"`
	// The path to a JSON service account that Spinnaker will use as
	// credentials. This is only needed if Spinnaker is not deployed on a
	// Google Compute Engine VM, or needs permissions not afforded to the VM
	// it is running on. See
	// https://cloud.google.com/compute/docs/access/service-accounts for
	// more information.
	JsonPath string `protobuf:"bytes,7,opt,name=jsonPath,proto3" json:"jsonPath,omitempty"`
	// A local directory to be used to stage source files for App Engine
	// deployments within Clouddriver.
	// Defaults to `/var/tmp/clouddriver`.
	LocalRepositoryDirectory string `protobuf:"bytes,8,opt,name=localRepositoryDirectory,proto3" json:"localRepositoryDirectory,omitempty"`
	// A list of regular expressions. Any service matching one of these
	// regexes will be ignored by Spinnaker.
	OmitServices []string `protobuf:"bytes,9,rep,name=omitServices,proto3" json:"omitServices,omitempty"`
	//  A list of regular expressions. Any version matching one of these
	//  regexes will be ignored by Spinnaker.
	OmitVersions []string `protobuf:"bytes,10,rep,name=omitVersions,proto3" json:"omitVersions,omitempty"`
	// The Google Cloud Platform project this Spinnaker account will manage.
	Project string `protobuf:"bytes,11,opt,name=project,proto3" json:"project,omitempty"`
	// Fiat permissions configuration.
	Permissions *Permissions `protobuf:"bytes,12,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// (Deprecated): List of required Fiat permission groups. Configure
	// `permissions` instead.
	RequiredGroupMemberships []string `protobuf:"bytes,13,rep,name=requiredGroupMemberships,proto3" json:"requiredGroupMemberships,omitempty"`
	// A list of regular expressions. Any service matching one of these
	// regexes will be indexed by Spinnaker (unless the service also
	// matches a regex in `omitServices`).
	Services []string `protobuf:"bytes,14,rep,name=services,proto3" json:"services,omitempty"`
	// The path to a `known_hosts` file to be used when connecting with a
	// remote git repository over SSH.
	SshKnownHostsFilePath string `protobuf:"bytes,15,opt,name=sshKnownHostsFilePath,proto3" json:"sshKnownHostsFilePath,omitempty"`
	// The path to an SSH private key to be used when connecting with a
	// remote git repository over SSH. If set, `sshPrivateKeyPassphrase` must
	// also be set.
	SshPrivateKeyFilePath string `protobuf:"bytes,16,opt,name=sshPrivateKeyFilePath,proto3" json:"sshPrivateKeyFilePath,omitempty"`
	// The passphrase to an SSH private key to be used when connecting with
	// a remote git repository over SSH. If set, `sshPrivateKeyFilePath` must
	// also be set.
	SshPrivateKeyPassphrase string `protobuf:"bytes,17,opt,name=sshPrivateKeyPassphrase,proto3" json:"sshPrivateKeyPassphrase,omitempty"`
	// Enabling this flag will allow Spinnaker to connect with a remote git
	// repository over SSH without verifying the server's IP address against
	// a `known_hosts` file. Defaults to false.
	SshTrustUnknownHosts bool `protobuf:"varint,18,opt,name=sshTrustUnknownHosts,proto3" json:"sshTrustUnknownHosts,omitempty"`
	// A list of regular expressions. Any version matching one of these
	// regexes will be indexed by Spinnaker (unless the version also matches
	// a regex in `omitVersions`).
	Versions []string `protobuf:"bytes,19,rep,name=versions,proto3" json:"versions,omitempty"`
	// The name of the account.
	Name                 string   `protobuf:"bytes,20,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppengineAccount) Reset()         { *m = AppengineAccount{} }
func (m *AppengineAccount) String() string { return proto.CompactTextString(m) }
func (*AppengineAccount) ProtoMessage()    {}
func (*AppengineAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_b058e5b683ee2a72, []int{1}
}

func (m *AppengineAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppengineAccount.Unmarshal(m, b)
}
func (m *AppengineAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppengineAccount.Marshal(b, m, deterministic)
}
func (m *AppengineAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppengineAccount.Merge(m, src)
}
func (m *AppengineAccount) XXX_Size() int {
	return xxx_messageInfo_AppengineAccount.Size(m)
}
func (m *AppengineAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_AppengineAccount.DiscardUnknown(m)
}

var xxx_messageInfo_AppengineAccount proto.InternalMessageInfo

func (m *AppengineAccount) GetCachingIntervalSeconds() int32 {
	if m != nil {
		return m.CachingIntervalSeconds
	}
	return 0
}

func (m *AppengineAccount) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *AppengineAccount) GetGcloudReleaseTrack() string {
	if m != nil {
		return m.GcloudReleaseTrack
	}
	return ""
}

func (m *AppengineAccount) GetGitHttpsUsername() string {
	if m != nil {
		return m.GitHttpsUsername
	}
	return ""
}

func (m *AppengineAccount) GetGitHttpsPassword() string {
	if m != nil {
		return m.GitHttpsPassword
	}
	return ""
}

func (m *AppengineAccount) GetGithubOAuthAccessToken() string {
	if m != nil {
		return m.GithubOAuthAccessToken
	}
	return ""
}

func (m *AppengineAccount) GetJsonPath() string {
	if m != nil {
		return m.JsonPath
	}
	return ""
}

func (m *AppengineAccount) GetLocalRepositoryDirectory() string {
	if m != nil {
		return m.LocalRepositoryDirectory
	}
	return ""
}

func (m *AppengineAccount) GetOmitServices() []string {
	if m != nil {
		return m.OmitServices
	}
	return nil
}

func (m *AppengineAccount) GetOmitVersions() []string {
	if m != nil {
		return m.OmitVersions
	}
	return nil
}

func (m *AppengineAccount) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *AppengineAccount) GetPermissions() *Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *AppengineAccount) GetRequiredGroupMemberships() []string {
	if m != nil {
		return m.RequiredGroupMemberships
	}
	return nil
}

func (m *AppengineAccount) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *AppengineAccount) GetSshKnownHostsFilePath() string {
	if m != nil {
		return m.SshKnownHostsFilePath
	}
	return ""
}

func (m *AppengineAccount) GetSshPrivateKeyFilePath() string {
	if m != nil {
		return m.SshPrivateKeyFilePath
	}
	return ""
}

func (m *AppengineAccount) GetSshPrivateKeyPassphrase() string {
	if m != nil {
		return m.SshPrivateKeyPassphrase
	}
	return ""
}

func (m *AppengineAccount) GetSshTrustUnknownHosts() bool {
	if m != nil {
		return m.SshTrustUnknownHosts
	}
	return false
}

func (m *AppengineAccount) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *AppengineAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*AppengineProvider)(nil), "proto.AppengineProvider")
	proto.RegisterType((*AppengineAccount)(nil), "proto.AppengineAccount")
}

func init() { proto.RegisterFile("appengine_provider.proto", fileDescriptor_b058e5b683ee2a72) }

var fileDescriptor_b058e5b683ee2a72 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0xd5, 0xfd, 0xec, 0xdc, 0x31, 0x36, 0x33, 0x98, 0xb5, 0xa7, 0x68, 0x12, 0x50, 0xf1,
	0xd0, 0x4a, 0xdb, 0x84, 0x10, 0x6f, 0x45, 0x08, 0x86, 0x26, 0x44, 0x95, 0x6d, 0x3c, 0xf0, 0x82,
	0x5c, 0xe7, 0xd4, 0x78, 0x4d, 0x6c, 0x73, 0xe7, 0x64, 0xda, 0xbf, 0xc0, 0x1f, 0x8d, 0x50, 0xdc,
	0x26, 0x6b, 0xb7, 0xf6, 0xa9, 0xb9, 0xfb, 0x7c, 0xcf, 0x77, 0x67, 0x7f, 0xcb, 0x84, 0x74, 0x0e,
	0xcc, 0x58, 0x1b, 0xf8, 0xed, 0xd0, 0x96, 0x3a, 0x01, 0xec, 0x39, 0xb4, 0xde, 0xf2, 0xcd, 0xf0,
	0x73, 0x7c, 0xe0, 0x00, 0x73, 0x4d, 0xa4, 0xad, 0xa1, 0x29, 0x39, 0xf9, 0xdb, 0x62, 0x07, 0x83,
	0xba, 0x6c, 0x38, 0xab, 0xe2, 0x82, 0x6d, 0x83, 0x91, 0xa3, 0x0c, 0x12, 0xd1, 0x8a, 0x5a, 0xdd,
	0x76, 0x5c, 0x87, 0xfc, 0x8c, 0xb5, 0xa5, 0x52, 0xb6, 0x30, 0x9e, 0xc4, 0x5a, 0xb4, 0xde, 0xed,
	0x9c, 0x1e, 0x4d, 0x4f, 0xea, 0x35, 0xa7, 0x0c, 0xa6, 0x3c, 0x6e, 0x84, 0xfc, 0x0d, 0xdb, 0x73,
	0xa8, 0x73, 0x89, 0xf7, 0x33, 0x26, 0xd6, 0xa3, 0x56, 0x77, 0x27, 0x7e, 0x94, 0x3d, 0xf9, 0xb7,
	0xc5, 0xf6, 0x1f, 0x1f, 0xc3, 0xdf, 0xb3, 0x57, 0x4a, 0xaa, 0x54, 0x9b, 0xf1, 0x37, 0xe3, 0x01,
	0x4b, 0x99, 0x5d, 0x81, 0xb2, 0x26, 0xa1, 0x30, 0xda, 0x66, 0xbc, 0x82, 0xf2, 0x88, 0x75, 0xc0,
	0x94, 0x1a, 0xad, 0xc9, 0xc1, 0x78, 0xb1, 0x16, 0x3a, 0xce, 0xa7, 0x78, 0x8f, 0xf1, 0xb1, 0xca,
	0x6c, 0x91, 0xc4, 0x90, 0x81, 0x24, 0xb8, 0x46, 0xa9, 0x26, 0xb3, 0xd1, 0x96, 0x10, 0xfe, 0x8e,
	0xed, 0x8f, 0xb5, 0xbf, 0xf0, 0xde, 0xd1, 0x0d, 0x01, 0x1a, 0x99, 0x83, 0xd8, 0x08, 0xea, 0x27,
	0xf9, 0x79, 0xed, 0x50, 0x12, 0xdd, 0x59, 0x4c, 0xc4, 0xe6, 0xa2, 0xb6, 0xce, 0x57, 0x1b, 0x8e,
	0xb5, 0x4f, 0x8b, 0xd1, 0x8f, 0x41, 0xe1, 0xd3, 0x81, 0x52, 0x40, 0x74, 0x6d, 0x27, 0x60, 0xc4,
	0x56, 0xa8, 0x58, 0x41, 0xf9, 0x31, 0x6b, 0xdf, 0x92, 0x35, 0x43, 0xe9, 0x53, 0xb1, 0x1d, 0x94,
	0x4d, 0xcc, 0x3f, 0x32, 0x91, 0x59, 0x25, 0xb3, 0x18, 0x9c, 0x25, 0xed, 0x2d, 0xde, 0x7f, 0xd6,
	0x08, 0xaa, 0xfa, 0x10, 0xed, 0xa0, 0x5d, 0xc9, 0xf9, 0x09, 0xdb, 0xb5, 0xb9, 0xf6, 0x57, 0x80,
	0xa5, 0x56, 0x40, 0x62, 0x27, 0x5a, 0xef, 0xee, 0xc4, 0x0b, 0xb9, 0x5a, 0xf3, 0x13, 0x30, 0xb8,
	0x49, 0xb0, 0x07, 0x4d, 0x9d, 0xab, 0x5c, 0xe4, 0xd0, 0xde, 0x82, 0xf2, 0xa2, 0x13, 0x5a, 0xd6,
	0x21, 0x3f, 0x67, 0x9d, 0x39, 0x2b, 0x8a, 0xdd, 0xa8, 0xd5, 0xed, 0x9c, 0xf2, 0x99, 0x91, 0x86,
	0x0f, 0x24, 0x9e, 0x97, 0x55, 0x3b, 0x21, 0xfc, 0x29, 0x34, 0x42, 0xf2, 0x15, 0x6d, 0xe1, 0xbe,
	0x43, 0x3e, 0x02, 0xa4, 0x54, 0x3b, 0x12, 0xcf, 0x42, 0xff, 0x95, 0xbc, 0xba, 0x2b, 0xaa, 0xf7,
	0xd9, 0x0b, 0xda, 0x26, 0xe6, 0xe7, 0xec, 0x25, 0x51, 0x7a, 0x69, 0xec, 0x9d, 0xb9, 0xb0, 0xe4,
	0xe9, 0x8b, 0xce, 0x20, 0x5c, 0xea, 0xf3, 0x30, 0xf5, 0x72, 0x38, 0xab, 0x1a, 0xa2, 0x2e, 0xa5,
	0x87, 0x4b, 0xb8, 0x6f, 0xaa, 0xf6, 0x9b, 0xaa, 0xa7, 0x90, 0x7f, 0x60, 0x47, 0x0b, 0xa0, 0x32,
	0x81, 0x4b, 0x51, 0x12, 0x88, 0x83, 0x50, 0xb7, 0x0a, 0xf3, 0x53, 0x76, 0x48, 0x94, 0x5e, 0x63,
	0x41, 0xfe, 0xc6, 0x4c, 0x9a, 0x79, 0x04, 0x0f, 0x7f, 0xd0, 0xa5, 0xac, 0xda, 0xba, 0xac, 0x5f,
	0xe8, 0xc5, 0x74, 0xeb, 0x3a, 0xe6, 0x9c, 0x6d, 0x04, 0x07, 0x1f, 0x86, 0xb6, 0xe1, 0xfb, 0xd3,
	0xdb, 0x5f, 0xaf, 0xa7, 0x5e, 0xeb, 0x29, 0x9b, 0xf7, 0xc9, 0x69, 0x63, 0xe4, 0x04, 0xb0, 0x3f,
	0xc9, 0x40, 0xfa, 0xbe, 0x74, 0xba, 0xaf, 0x32, 0x0d, 0xc6, 0x8f, 0xb6, 0xc2, 0x53, 0x9d, 0xfd,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0x76, 0x0c, 0x07, 0xba, 0x73, 0x04, 0x00, 0x00,
}
