// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bitbucket.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Bitbucket artifact provider.
type BitbucketProvider struct {
	// Whether the Bitbucket artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured Bitbucket accounts.
	Accounts             []*BitbucketAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BitbucketProvider) Reset()         { *m = BitbucketProvider{} }
func (m *BitbucketProvider) String() string { return proto.CompactTextString(m) }
func (*BitbucketProvider) ProtoMessage()    {}
func (*BitbucketProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a67d55d9afc1bd, []int{0}
}

func (m *BitbucketProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitbucketProvider.Unmarshal(m, b)
}
func (m *BitbucketProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitbucketProvider.Marshal(b, m, deterministic)
}
func (m *BitbucketProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitbucketProvider.Merge(m, src)
}
func (m *BitbucketProvider) XXX_Size() int {
	return xxx_messageInfo_BitbucketProvider.Size(m)
}
func (m *BitbucketProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_BitbucketProvider.DiscardUnknown(m)
}

var xxx_messageInfo_BitbucketProvider proto.InternalMessageInfo

func (m *BitbucketProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *BitbucketProvider) GetAccounts() []*BitbucketAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for a Bitbucket artifact account.
type BitbucketAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The username of the account. Either `username` and `password` should be
	// set, or `usernamePasswordFile` should be set.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The password of the account. Either `username` and `password` should be
	// set, or `usernamePasswordFile` should be set.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// The path to a file containing the username and password of the account
	// in the format `${username}:${password}`. Either `username` and
	// `password` should be set, or `usernamePasswordFile` should be set.
	UsernamePasswordFile string   `protobuf:"bytes,4,opt,name=usernamePasswordFile,proto3" json:"usernamePasswordFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitbucketAccount) Reset()         { *m = BitbucketAccount{} }
func (m *BitbucketAccount) String() string { return proto.CompactTextString(m) }
func (*BitbucketAccount) ProtoMessage()    {}
func (*BitbucketAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a67d55d9afc1bd, []int{1}
}

func (m *BitbucketAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitbucketAccount.Unmarshal(m, b)
}
func (m *BitbucketAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitbucketAccount.Marshal(b, m, deterministic)
}
func (m *BitbucketAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitbucketAccount.Merge(m, src)
}
func (m *BitbucketAccount) XXX_Size() int {
	return xxx_messageInfo_BitbucketAccount.Size(m)
}
func (m *BitbucketAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BitbucketAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BitbucketAccount proto.InternalMessageInfo

func (m *BitbucketAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BitbucketAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *BitbucketAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *BitbucketAccount) GetUsernamePasswordFile() string {
	if m != nil {
		return m.UsernamePasswordFile
	}
	return ""
}

func init() {
	proto.RegisterType((*BitbucketProvider)(nil), "proto.BitbucketProvider")
	proto.RegisterType((*BitbucketAccount)(nil), "proto.BitbucketAccount")
}

func init() { proto.RegisterFile("bitbucket.proto", fileDescriptor_53a67d55d9afc1bd) }

var fileDescriptor_53a67d55d9afc1bd = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xca, 0x2c, 0x49,
	0x2a, 0x4d, 0xce, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a,
	0x49, 0x5c, 0x82, 0x4e, 0x30, 0x99, 0x80, 0xa2, 0xfc, 0xb2, 0xcc, 0x94, 0xd4, 0x22, 0x21, 0x09,
	0x2e, 0xf6, 0xd4, 0xbc, 0xc4, 0xa4, 0x9c, 0xd4, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20,
	0x18, 0x57, 0xc8, 0x98, 0x8b, 0x23, 0x31, 0x39, 0x39, 0xbf, 0x34, 0xaf, 0xa4, 0x58, 0x82, 0x49,
	0x81, 0x59, 0x83, 0xdb, 0x48, 0x1c, 0x62, 0x9e, 0x1e, 0xdc, 0x14, 0x47, 0x88, 0x7c, 0x10, 0x5c,
	0xa1, 0xd2, 0x24, 0x46, 0x2e, 0x01, 0x74, 0x69, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54,
	0xb0, 0x05, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x14, 0x17, 0x47, 0x69, 0x71, 0x6a, 0x11, 0x58, 0x9c,
	0x09, 0x2c, 0x0e, 0xe7, 0x83, 0xe4, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98,
	0x21, 0x72, 0x30, 0xbe, 0x90, 0x11, 0x97, 0x08, 0x4c, 0x5d, 0x00, 0x54, 0xcc, 0x2d, 0x33, 0x27,
	0x55, 0x82, 0x05, 0xac, 0x0e, 0xab, 0x5c, 0x12, 0x1b, 0xd8, 0xd9, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x80, 0x53, 0x51, 0xa6, 0x19, 0x01, 0x00, 0x00,
}
