// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bitbucket_artifact_provider.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Bitbucket artifact provider.
type BitbucketArtifactProvider struct {
	// Whether the Bitbucket artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured Bitbucket accounts.
	Accounts             []*BitbucketArtifactAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BitbucketArtifactProvider) Reset()         { *m = BitbucketArtifactProvider{} }
func (m *BitbucketArtifactProvider) String() string { return proto.CompactTextString(m) }
func (*BitbucketArtifactProvider) ProtoMessage()    {}
func (*BitbucketArtifactProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_059e80e3d0fd71a0, []int{0}
}

func (m *BitbucketArtifactProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitbucketArtifactProvider.Unmarshal(m, b)
}
func (m *BitbucketArtifactProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitbucketArtifactProvider.Marshal(b, m, deterministic)
}
func (m *BitbucketArtifactProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitbucketArtifactProvider.Merge(m, src)
}
func (m *BitbucketArtifactProvider) XXX_Size() int {
	return xxx_messageInfo_BitbucketArtifactProvider.Size(m)
}
func (m *BitbucketArtifactProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_BitbucketArtifactProvider.DiscardUnknown(m)
}

var xxx_messageInfo_BitbucketArtifactProvider proto.InternalMessageInfo

func (m *BitbucketArtifactProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *BitbucketArtifactProvider) GetAccounts() []*BitbucketArtifactAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for a Bitbucket artifact account.
type BitbucketArtifactAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The username of the account. Either `username` and `password` should be
	// set, or `usernamePasswordFile` should be set.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The password of the account. Either `username` and `password` should be
	// set, or `usernamePasswordFile` should be set.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// The path to a file containing the username and password of the account
	// in the format `${username}:${password}`. Either `username` and
	// `password` should be set, or `usernamePasswordFile` should be set.
	UsernamePasswordFile string   `protobuf:"bytes,4,opt,name=usernamePasswordFile,proto3" json:"usernamePasswordFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitbucketArtifactAccount) Reset()         { *m = BitbucketArtifactAccount{} }
func (m *BitbucketArtifactAccount) String() string { return proto.CompactTextString(m) }
func (*BitbucketArtifactAccount) ProtoMessage()    {}
func (*BitbucketArtifactAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_059e80e3d0fd71a0, []int{1}
}

func (m *BitbucketArtifactAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitbucketArtifactAccount.Unmarshal(m, b)
}
func (m *BitbucketArtifactAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitbucketArtifactAccount.Marshal(b, m, deterministic)
}
func (m *BitbucketArtifactAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitbucketArtifactAccount.Merge(m, src)
}
func (m *BitbucketArtifactAccount) XXX_Size() int {
	return xxx_messageInfo_BitbucketArtifactAccount.Size(m)
}
func (m *BitbucketArtifactAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BitbucketArtifactAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BitbucketArtifactAccount proto.InternalMessageInfo

func (m *BitbucketArtifactAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BitbucketArtifactAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *BitbucketArtifactAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *BitbucketArtifactAccount) GetUsernamePasswordFile() string {
	if m != nil {
		return m.UsernamePasswordFile
	}
	return ""
}

func init() {
	proto.RegisterType((*BitbucketArtifactProvider)(nil), "proto.BitbucketArtifactProvider")
	proto.RegisterType((*BitbucketArtifactAccount)(nil), "proto.BitbucketArtifactAccount")
}

func init() { proto.RegisterFile("bitbucket_artifact_provider.proto", fileDescriptor_059e80e3d0fd71a0) }

var fileDescriptor_059e80e3d0fd71a0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0xca, 0x2c, 0x49,
	0x2a, 0x4d, 0xce, 0x4e, 0x2d, 0x89, 0x4f, 0x2c, 0x2a, 0xc9, 0x4c, 0x4b, 0x4c, 0x2e, 0x89, 0x2f,
	0x28, 0xca, 0x2f, 0xcb, 0x4c, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x45, 0x5c, 0x92, 0x4e, 0x30, 0xb5, 0x8e, 0x50, 0xa5, 0x01, 0x50, 0x95, 0x42, 0x12,
	0x5c, 0xec, 0xa9, 0x79, 0x89, 0x49, 0x39, 0xa9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41,
	0x30, 0xae, 0x90, 0x35, 0x17, 0x47, 0x62, 0x72, 0x72, 0x7e, 0x69, 0x5e, 0x49, 0xb1, 0x04, 0x93,
	0x02, 0xb3, 0x06, 0xb7, 0x91, 0x3c, 0xc4, 0x5c, 0x3d, 0x0c, 0xd3, 0x1c, 0x21, 0xea, 0x82, 0xe0,
	0x1a, 0x94, 0x66, 0x31, 0x72, 0x49, 0xe0, 0x52, 0x26, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b,
	0x0a, 0xb6, 0x90, 0x33, 0x08, 0xcc, 0x16, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0x02, 0x8b,
	0x33, 0x81, 0xc5, 0xe1, 0x7c, 0x90, 0x5c, 0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04,
	0x33, 0x44, 0x0e, 0xc6, 0x17, 0x32, 0xe2, 0x12, 0x81, 0xa9, 0x0b, 0x80, 0x8a, 0xb9, 0x65, 0xe6,
	0xa4, 0x4a, 0xb0, 0x80, 0xd5, 0x61, 0x95, 0x4b, 0x62, 0x03, 0x7b, 0xc3, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0x86, 0xe6, 0xdb, 0x43, 0x01, 0x00, 0x00,
}
