// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloudfoundry_provider.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Cloud Foundry provider.
type CloudFoundryProvider struct {
	// Whether the provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured accounts.
	Accounts []*CloudFoundryAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// The name of the primary account.
	PrimaryAccount       string   `protobuf:"bytes,3,opt,name=primaryAccount,proto3" json:"primaryAccount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudFoundryProvider) Reset()         { *m = CloudFoundryProvider{} }
func (m *CloudFoundryProvider) String() string { return proto.CompactTextString(m) }
func (*CloudFoundryProvider) ProtoMessage()    {}
func (*CloudFoundryProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcaecade4cf109a6, []int{0}
}

func (m *CloudFoundryProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudFoundryProvider.Unmarshal(m, b)
}
func (m *CloudFoundryProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudFoundryProvider.Marshal(b, m, deterministic)
}
func (m *CloudFoundryProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudFoundryProvider.Merge(m, src)
}
func (m *CloudFoundryProvider) XXX_Size() int {
	return xxx_messageInfo_CloudFoundryProvider.Size(m)
}
func (m *CloudFoundryProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudFoundryProvider.DiscardUnknown(m)
}

var xxx_messageInfo_CloudFoundryProvider proto.InternalMessageInfo

func (m *CloudFoundryProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CloudFoundryProvider) GetAccounts() []*CloudFoundryAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *CloudFoundryProvider) GetPrimaryAccount() string {
	if m != nil {
		return m.PrimaryAccount
	}
	return ""
}

// Configuration for a Spinnaker Cloud Foundry account.
type CloudFoundryAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// (Required) Host of the Cloud Foundry Foundation API endpoint
	// (e.g., `api.sys.somesystem.com`).
	Api string `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	// HTTP(S) URL of the Apps Manager application for the Cloud Foundry
	// Foundation (e.g., `https://apps.sys.somesystem.com`).
	AppsManagerUri string `protobuf:"bytes,3,opt,name=appsManagerUri,proto3" json:"appsManagerUri,omitempty"`
	// The environment name for the account. Many accounts can share the
	// same environment (e.g., dev, test, prod).
	Environment string `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	// HTTP(S) URL of the metrics application for the Cloud Foundry Foundation
	// (e.g., `https://metrics.sys.somesystem.com`).
	MetricsUri string `protobuf:"bytes,5,opt,name=metricsUri,proto3" json:"metricsUri,omitempty"`
	// (Required) Password for the account to use for this Cloud Foundry
	// Foundation.
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	// (Default: `false`) Skip SSL server certificate validation of the API
	// endpoint.
	SkipSslValidation bool `protobuf:"varint,7,opt,name=skipSslValidation,proto3" json:"skipSslValidation,omitempty"`
	// (Required) User name for the account to use for this Cloud Foundry
	// Foundation.
	User string `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	// Fiat permissions configuration.
	Permissions *Permissions `protobuf:"bytes,9,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// (Deprecated): List of required Fiat permission groups. Configure
	// `permissions` instead.
	RequiredGroupMemberships []string `protobuf:"bytes,10,rep,name=requiredGroupMemberships,proto3" json:"requiredGroupMemberships,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *CloudFoundryAccount) Reset()         { *m = CloudFoundryAccount{} }
func (m *CloudFoundryAccount) String() string { return proto.CompactTextString(m) }
func (*CloudFoundryAccount) ProtoMessage()    {}
func (*CloudFoundryAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcaecade4cf109a6, []int{1}
}

func (m *CloudFoundryAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudFoundryAccount.Unmarshal(m, b)
}
func (m *CloudFoundryAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudFoundryAccount.Marshal(b, m, deterministic)
}
func (m *CloudFoundryAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudFoundryAccount.Merge(m, src)
}
func (m *CloudFoundryAccount) XXX_Size() int {
	return xxx_messageInfo_CloudFoundryAccount.Size(m)
}
func (m *CloudFoundryAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudFoundryAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CloudFoundryAccount proto.InternalMessageInfo

func (m *CloudFoundryAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CloudFoundryAccount) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CloudFoundryAccount) GetAppsManagerUri() string {
	if m != nil {
		return m.AppsManagerUri
	}
	return ""
}

func (m *CloudFoundryAccount) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *CloudFoundryAccount) GetMetricsUri() string {
	if m != nil {
		return m.MetricsUri
	}
	return ""
}

func (m *CloudFoundryAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CloudFoundryAccount) GetSkipSslValidation() bool {
	if m != nil {
		return m.SkipSslValidation
	}
	return false
}

func (m *CloudFoundryAccount) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *CloudFoundryAccount) GetPermissions() *Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *CloudFoundryAccount) GetRequiredGroupMemberships() []string {
	if m != nil {
		return m.RequiredGroupMemberships
	}
	return nil
}

func init() {
	proto.RegisterType((*CloudFoundryProvider)(nil), "proto.CloudFoundryProvider")
	proto.RegisterType((*CloudFoundryAccount)(nil), "proto.CloudFoundryAccount")
}

func init() { proto.RegisterFile("cloudfoundry_provider.proto", fileDescriptor_bcaecade4cf109a6) }

var fileDescriptor_bcaecade4cf109a6 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x4b, 0xeb, 0x40,
	0x10, 0x27, 0x4d, 0x3f, 0x92, 0x09, 0x3c, 0x5e, 0xf7, 0xbd, 0xc3, 0x52, 0x41, 0x42, 0x0f, 0x92,
	0x83, 0xf4, 0x50, 0xc5, 0x83, 0x37, 0x11, 0xf4, 0x54, 0x28, 0x11, 0xbd, 0xca, 0x36, 0x19, 0x75,
	0x31, 0xd9, 0x5d, 0x67, 0x93, 0x8a, 0xff, 0x85, 0xff, 0xac, 0x77, 0xc9, 0xa6, 0xad, 0xf1, 0xeb,
	0x94, 0x99, 0xdf, 0xd7, 0x64, 0x66, 0x61, 0x2f, 0x2b, 0x74, 0x9d, 0xdf, 0xe9, 0x5a, 0xe5, 0xf4,
	0x72, 0x6b, 0x48, 0xaf, 0x65, 0x8e, 0x34, 0x33, 0xa4, 0x2b, 0xcd, 0x06, 0xee, 0x33, 0x19, 0x1b,
	0xa4, 0x52, 0x5a, 0x2b, 0xb5, 0xb2, 0x2d, 0x33, 0x7d, 0xf5, 0xe0, 0xff, 0x79, 0xe3, 0xbc, 0x68,
	0x9d, 0xcb, 0x8d, 0x91, 0x71, 0x18, 0xa1, 0x12, 0xab, 0x02, 0x73, 0xee, 0xc5, 0x5e, 0x12, 0xa4,
	0xdb, 0x96, 0x9d, 0x40, 0x20, 0xb2, 0x4c, 0xd7, 0xaa, 0xb2, 0xbc, 0x17, 0xfb, 0x49, 0x34, 0x9f,
	0xb4, 0x61, 0xb3, 0x6e, 0xd0, 0x59, 0x2b, 0x49, 0x77, 0x5a, 0x76, 0x00, 0x7f, 0x0c, 0xc9, 0x52,
	0xec, 0x38, 0xee, 0xc7, 0x5e, 0x12, 0xa6, 0x5f, 0xd0, 0xe9, 0x5b, 0x0f, 0xfe, 0xfd, 0x90, 0xc4,
	0x18, 0xf4, 0x95, 0x28, 0xd1, 0xfd, 0x4e, 0x98, 0xba, 0x9a, 0xfd, 0x05, 0x5f, 0x18, 0xc9, 0x7b,
	0x0e, 0x6a, 0xca, 0x66, 0x8a, 0x30, 0xc6, 0x2e, 0x84, 0x12, 0xf7, 0x48, 0xd7, 0x24, 0xb7, 0x53,
	0x3e, 0xa3, 0x2c, 0x86, 0x08, 0xd5, 0x5a, 0x92, 0x56, 0x25, 0xaa, 0x8a, 0xf7, 0x9d, 0xa8, 0x0b,
	0xb1, 0x7d, 0x80, 0x12, 0x2b, 0x92, 0x99, 0x6d, 0x52, 0x06, 0x4e, 0xd0, 0x41, 0xd8, 0x04, 0x02,
	0x23, 0xac, 0x7d, 0xd6, 0x94, 0xf3, 0xa1, 0x63, 0x77, 0x3d, 0x3b, 0x84, 0xb1, 0x7d, 0x94, 0xe6,
	0xca, 0x16, 0x37, 0xa2, 0x90, 0xb9, 0xa8, 0xa4, 0x56, 0x7c, 0xe4, 0xee, 0xf8, 0x9d, 0x68, 0x36,
	0xab, 0x2d, 0x12, 0x0f, 0xda, 0xcd, 0x9a, 0x9a, 0x1d, 0x43, 0xd4, 0x79, 0x2d, 0x1e, 0xc6, 0x5e,
	0x12, 0xcd, 0xd9, 0xe6, 0xd0, 0xcb, 0x0f, 0x26, 0xed, 0xca, 0xd8, 0x29, 0x70, 0xc2, 0xa7, 0x5a,
	0x12, 0xe6, 0x97, 0xa4, 0x6b, 0xb3, 0xc0, 0x72, 0x85, 0x64, 0x1f, 0xa4, 0xb1, 0x1c, 0x62, 0x3f,
	0x09, 0xd3, 0x5f, 0xf9, 0xd5, 0xd0, 0x65, 0x1f, 0xbd, 0x07, 0x00, 0x00, 0xff, 0xff, 0x81, 0x50,
	0xc0, 0x69, 0x4a, 0x02, 0x00, 0x00,
}
