// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clouddriver.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClouddriverConfig struct {
	Kubernetes           *Kubernetes `protobuf:"bytes,1,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	Google               *Google     `protobuf:"bytes,2,opt,name=google,proto3" json:"google,omitempty"`
	Appengine            *Appengine  `protobuf:"bytes,3,opt,name=appengine,proto3" json:"appengine,omitempty"`
	Aws                  *Aws        `protobuf:"bytes,4,opt,name=aws,proto3" json:"aws,omitempty"`
	Azure                *Azure      `protobuf:"bytes,5,opt,name=azure,proto3" json:"azure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClouddriverConfig) Reset()         { *m = ClouddriverConfig{} }
func (m *ClouddriverConfig) String() string { return proto.CompactTextString(m) }
func (*ClouddriverConfig) ProtoMessage()    {}
func (*ClouddriverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0260082fb56e518f, []int{0}
}

func (m *ClouddriverConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClouddriverConfig.Unmarshal(m, b)
}
func (m *ClouddriverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClouddriverConfig.Marshal(b, m, deterministic)
}
func (m *ClouddriverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClouddriverConfig.Merge(m, src)
}
func (m *ClouddriverConfig) XXX_Size() int {
	return xxx_messageInfo_ClouddriverConfig.Size(m)
}
func (m *ClouddriverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClouddriverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClouddriverConfig proto.InternalMessageInfo

func (m *ClouddriverConfig) GetKubernetes() *Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

func (m *ClouddriverConfig) GetGoogle() *Google {
	if m != nil {
		return m.Google
	}
	return nil
}

func (m *ClouddriverConfig) GetAppengine() *Appengine {
	if m != nil {
		return m.Appengine
	}
	return nil
}

func (m *ClouddriverConfig) GetAws() *Aws {
	if m != nil {
		return m.Aws
	}
	return nil
}

func (m *ClouddriverConfig) GetAzure() *Azure {
	if m != nil {
		return m.Azure
	}
	return nil
}

func init() {
	proto.RegisterType((*ClouddriverConfig)(nil), "proto.ClouddriverConfig")
}

func init() { proto.RegisterFile("clouddriver.proto", fileDescriptor_0260082fb56e518f) }

var fileDescriptor_0260082fb56e518f = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x6a, 0x84, 0x30,
	0x14, 0x40, 0xb1, 0x56, 0xc1, 0xaf, 0xa5, 0x9a, 0x55, 0x90, 0x2e, 0x8a, 0x50, 0xe8, 0x4a, 0x68,
	0x7b, 0x82, 0xe2, 0xa2, 0x8b, 0xee, 0x72, 0x83, 0x58, 0xd3, 0x20, 0x23, 0x89, 0x44, 0x1d, 0x61,
	0x2e, 0x3b, 0x57, 0x19, 0xfc, 0x49, 0x74, 0x56, 0x21, 0xef, 0xbd, 0xf0, 0x7f, 0xa0, 0xf8, 0x1b,
	0xf4, 0xd2, 0x75, 0xa6, 0x3f, 0x0b, 0x53, 0x8f, 0x46, 0xcf, 0x9a, 0x44, 0x78, 0x94, 0xf9, 0x69,
	0x69, 0x85, 0x51, 0x62, 0x16, 0x93, 0x15, 0x65, 0x26, 0xb5, 0x96, 0x83, 0x70, 0xb7, 0x67, 0x3e,
	0x8e, 0x42, 0xc9, 0x5e, 0x79, 0x90, 0xf0, 0xd5, 0x97, 0x29, 0xbf, 0x2c, 0xc6, 0xf1, 0xea, 0x1a,
	0x40, 0xd1, 0x1c, 0x53, 0x1a, 0xad, 0xfe, 0x7b, 0x49, 0x3e, 0x00, 0x8e, 0x01, 0x34, 0x78, 0x0d,
	0xde, 0xd3, 0xcf, 0xc2, 0xbe, 0xa8, 0x7f, 0x77, 0xc1, 0xee, 0x22, 0xf2, 0x06, 0xb1, 0xdd, 0x80,
	0x3e, 0x60, 0xfe, 0xe4, 0xf2, 0x1f, 0x84, 0xcc, 0x49, 0x52, 0x43, 0xb2, 0xaf, 0x46, 0x43, 0x2c,
	0x73, 0x57, 0x7e, 0x7b, 0xce, 0x8e, 0x84, 0xbc, 0x40, 0xc8, 0xd7, 0x89, 0x3e, 0x62, 0x09, 0xbe,
	0x5c, 0x27, 0xb6, 0x61, 0x52, 0x41, 0x84, 0x9f, 0xa1, 0x11, 0xfa, 0xcc, 0xfb, 0x8d, 0x31, 0xab,
	0xda, 0x18, 0xd9, 0xd7, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x19, 0x31, 0xae, 0x46, 0x4d, 0x01, 0x00,
	0x00,
}
