// Code generated by protoc-gen-go. DO NOT EDIT.
// source: front50.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Front50Config struct {
	Spinnaker            *Front50Config_Spinnaker `protobuf:"bytes,1,opt,name=spinnaker,proto3" json:"spinnaker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Front50Config) Reset()         { *m = Front50Config{} }
func (m *Front50Config) String() string { return proto.CompactTextString(m) }
func (*Front50Config) ProtoMessage()    {}
func (*Front50Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_8475b88be97fe157, []int{0}
}

func (m *Front50Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Front50Config.Unmarshal(m, b)
}
func (m *Front50Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Front50Config.Marshal(b, m, deterministic)
}
func (m *Front50Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Front50Config.Merge(m, src)
}
func (m *Front50Config) XXX_Size() int {
	return xxx_messageInfo_Front50Config.Size(m)
}
func (m *Front50Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Front50Config.DiscardUnknown(m)
}

var xxx_messageInfo_Front50Config proto.InternalMessageInfo

func (m *Front50Config) GetSpinnaker() *Front50Config_Spinnaker {
	if m != nil {
		return m.Spinnaker
	}
	return nil
}

type Front50Config_Spinnaker struct {
	PersistentStoreType  string   `protobuf:"bytes,1,opt,name=persistentStoreType,proto3" json:"persistentStoreType,omitempty"`
	Gcs                  *GCS     `protobuf:"bytes,2,opt,name=gcs,proto3" json:"gcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Front50Config_Spinnaker) Reset()         { *m = Front50Config_Spinnaker{} }
func (m *Front50Config_Spinnaker) String() string { return proto.CompactTextString(m) }
func (*Front50Config_Spinnaker) ProtoMessage()    {}
func (*Front50Config_Spinnaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_8475b88be97fe157, []int{0, 0}
}

func (m *Front50Config_Spinnaker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Front50Config_Spinnaker.Unmarshal(m, b)
}
func (m *Front50Config_Spinnaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Front50Config_Spinnaker.Marshal(b, m, deterministic)
}
func (m *Front50Config_Spinnaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Front50Config_Spinnaker.Merge(m, src)
}
func (m *Front50Config_Spinnaker) XXX_Size() int {
	return xxx_messageInfo_Front50Config_Spinnaker.Size(m)
}
func (m *Front50Config_Spinnaker) XXX_DiscardUnknown() {
	xxx_messageInfo_Front50Config_Spinnaker.DiscardUnknown(m)
}

var xxx_messageInfo_Front50Config_Spinnaker proto.InternalMessageInfo

func (m *Front50Config_Spinnaker) GetPersistentStoreType() string {
	if m != nil {
		return m.PersistentStoreType
	}
	return ""
}

func (m *Front50Config_Spinnaker) GetGcs() *GCS {
	if m != nil {
		return m.Gcs
	}
	return nil
}

func init() {
	proto.RegisterType((*Front50Config)(nil), "proto.Front50Config")
	proto.RegisterType((*Front50Config_Spinnaker)(nil), "proto.Front50Config.Spinnaker")
}

func init() { proto.RegisterFile("front50.proto", fileDescriptor_8475b88be97fe157) }

var fileDescriptor_8475b88be97fe157 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2b, 0xca, 0xcf,
	0x2b, 0x31, 0x35, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x12, 0x05,
	0xa9, 0x45, 0xc5, 0x99, 0xc5, 0x25, 0xa9, 0x79, 0x25, 0xf1, 0xc5, 0x25, 0xf9, 0x45, 0x89, 0xe9,
	0xa9, 0x10, 0x05, 0x4a, 0xab, 0x18, 0xb9, 0x78, 0xdd, 0x20, 0x5a, 0x9c, 0xf3, 0xf3, 0xd2, 0x32,
	0xd3, 0x85, 0x6c, 0xb8, 0x38, 0x8b, 0x0b, 0x32, 0xf3, 0xf2, 0x12, 0xb3, 0x53, 0x8b, 0x24, 0x18,
	0x15, 0x18, 0x35, 0xb8, 0x8d, 0xe4, 0x20, 0x8a, 0xf5, 0x50, 0x14, 0xea, 0x05, 0xc3, 0x54, 0x05,
	0x21, 0x34, 0x48, 0x45, 0x73, 0x71, 0xc2, 0xc5, 0x85, 0x0c, 0xb8, 0x84, 0x11, 0x16, 0x07, 0x97,
	0xe4, 0x17, 0xa5, 0x86, 0x54, 0x16, 0xa4, 0x82, 0x0d, 0xe5, 0x0c, 0xc2, 0x26, 0x25, 0x24, 0xc3,
	0xc5, 0x9c, 0x9e, 0x5c, 0x2c, 0xc1, 0x04, 0xb6, 0x96, 0x0b, 0x6a, 0xad, 0xbb, 0x73, 0x70, 0x10,
	0x48, 0xd8, 0x49, 0x3d, 0x4a, 0x35, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57,
	0x1f, 0x6e, 0xa9, 0x7e, 0x76, 0x4e, 0x6a, 0x62, 0x89, 0x7e, 0x62, 0x41, 0xa6, 0x7e, 0x72, 0x4e,
	0x66, 0x6a, 0x5e, 0x49, 0x12, 0x1b, 0x58, 0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xd0,
	0x33, 0x51, 0x0e, 0x01, 0x00, 0x00,
}
