// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Google Cloud Storage (GCS) artifact provider.
type GcsProvider struct {
	// Whether the GCS artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured GCS accounts.
	Accounts             []*GcsAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GcsProvider) Reset()         { *m = GcsProvider{} }
func (m *GcsProvider) String() string { return proto.CompactTextString(m) }
func (*GcsProvider) ProtoMessage()    {}
func (*GcsProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2126060daa3deb3, []int{0}
}

func (m *GcsProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcsProvider.Unmarshal(m, b)
}
func (m *GcsProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcsProvider.Marshal(b, m, deterministic)
}
func (m *GcsProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcsProvider.Merge(m, src)
}
func (m *GcsProvider) XXX_Size() int {
	return xxx_messageInfo_GcsProvider.Size(m)
}
func (m *GcsProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_GcsProvider.DiscardUnknown(m)
}

var xxx_messageInfo_GcsProvider proto.InternalMessageInfo

func (m *GcsProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *GcsProvider) GetAccounts() []*GcsAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for a GCS artifact account.
type GcsAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The path to a JSON key for a GCP service account with which to
	// authenticate. The service account must have the `roles/storage.admin`
	// role enabled.
	JsonPath             string   `protobuf:"bytes,2,opt,name=jsonPath,proto3" json:"jsonPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcsAccount) Reset()         { *m = GcsAccount{} }
func (m *GcsAccount) String() string { return proto.CompactTextString(m) }
func (*GcsAccount) ProtoMessage()    {}
func (*GcsAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2126060daa3deb3, []int{1}
}

func (m *GcsAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcsAccount.Unmarshal(m, b)
}
func (m *GcsAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcsAccount.Marshal(b, m, deterministic)
}
func (m *GcsAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcsAccount.Merge(m, src)
}
func (m *GcsAccount) XXX_Size() int {
	return xxx_messageInfo_GcsAccount.Size(m)
}
func (m *GcsAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_GcsAccount.DiscardUnknown(m)
}

var xxx_messageInfo_GcsAccount proto.InternalMessageInfo

func (m *GcsAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GcsAccount) GetJsonPath() string {
	if m != nil {
		return m.JsonPath
	}
	return ""
}

func init() {
	proto.RegisterType((*GcsProvider)(nil), "proto.GcsProvider")
	proto.RegisterType((*GcsAccount)(nil), "proto.GcsAccount")
}

func init() { proto.RegisterFile("gcs.proto", fileDescriptor_c2126060daa3deb3) }

var fileDescriptor_c2126060daa3deb3 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4f, 0x2e, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x61, 0x5c, 0xdc, 0xee, 0xc9, 0xc5,
	0x01, 0x45, 0xf9, 0x65, 0x99, 0x29, 0xa9, 0x45, 0x42, 0x12, 0x5c, 0xec, 0xa9, 0x79, 0x89, 0x49,
	0x39, 0xa9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x2e, 0x17, 0x47,
	0x62, 0x72, 0x72, 0x7e, 0x69, 0x5e, 0x49, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x20,
	0xc4, 0x24, 0x3d, 0xf7, 0xe4, 0x62, 0x47, 0x88, 0x4c, 0x10, 0x5c, 0x89, 0x92, 0x0d, 0x17, 0x17,
	0x42, 0x5c, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x15, 0x6c, 0x26, 0x67, 0x10, 0x98, 0x2d,
	0x24, 0xc5, 0xc5, 0x91, 0x55, 0x9c, 0x9f, 0x17, 0x90, 0x58, 0x92, 0x21, 0xc1, 0x04, 0x16, 0x87,
	0xf3, 0x93, 0xd8, 0xc0, 0x26, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x63, 0x42, 0x42, 0x22,
	0xb0, 0x00, 0x00, 0x00,
}
