// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcs_artifact_provider.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Google Cloud Storage (GCS) artifact provider.
type GcsArtifactProvider struct {
	// Whether the GCS artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured GCS accounts.
	Accounts             []*GcsArtifactAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GcsArtifactProvider) Reset()         { *m = GcsArtifactProvider{} }
func (m *GcsArtifactProvider) String() string { return proto.CompactTextString(m) }
func (*GcsArtifactProvider) ProtoMessage()    {}
func (*GcsArtifactProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_0693f519f252456e, []int{0}
}

func (m *GcsArtifactProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcsArtifactProvider.Unmarshal(m, b)
}
func (m *GcsArtifactProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcsArtifactProvider.Marshal(b, m, deterministic)
}
func (m *GcsArtifactProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcsArtifactProvider.Merge(m, src)
}
func (m *GcsArtifactProvider) XXX_Size() int {
	return xxx_messageInfo_GcsArtifactProvider.Size(m)
}
func (m *GcsArtifactProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_GcsArtifactProvider.DiscardUnknown(m)
}

var xxx_messageInfo_GcsArtifactProvider proto.InternalMessageInfo

func (m *GcsArtifactProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *GcsArtifactProvider) GetAccounts() []*GcsArtifactAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for a GCS artifact account.
type GcsArtifactAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The path to a JSON key for a GCP service account with which to
	// authenticate. The service account must have the `roles/storage.admin`
	// role enabled.
	JsonPath             string   `protobuf:"bytes,2,opt,name=jsonPath,proto3" json:"jsonPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcsArtifactAccount) Reset()         { *m = GcsArtifactAccount{} }
func (m *GcsArtifactAccount) String() string { return proto.CompactTextString(m) }
func (*GcsArtifactAccount) ProtoMessage()    {}
func (*GcsArtifactAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_0693f519f252456e, []int{1}
}

func (m *GcsArtifactAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcsArtifactAccount.Unmarshal(m, b)
}
func (m *GcsArtifactAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcsArtifactAccount.Marshal(b, m, deterministic)
}
func (m *GcsArtifactAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcsArtifactAccount.Merge(m, src)
}
func (m *GcsArtifactAccount) XXX_Size() int {
	return xxx_messageInfo_GcsArtifactAccount.Size(m)
}
func (m *GcsArtifactAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_GcsArtifactAccount.DiscardUnknown(m)
}

var xxx_messageInfo_GcsArtifactAccount proto.InternalMessageInfo

func (m *GcsArtifactAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GcsArtifactAccount) GetJsonPath() string {
	if m != nil {
		return m.JsonPath
	}
	return ""
}

func init() {
	proto.RegisterType((*GcsArtifactProvider)(nil), "proto.GcsArtifactProvider")
	proto.RegisterType((*GcsArtifactAccount)(nil), "proto.GcsArtifactAccount")
}

func init() { proto.RegisterFile("gcs_artifact_provider.proto", fileDescriptor_0693f519f252456e) }

var fileDescriptor_0693f519f252456e = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x4f, 0x2e, 0x8e,
	0x4f, 0x2c, 0x2a, 0xc9, 0x4c, 0x4b, 0x4c, 0x2e, 0x89, 0x2f, 0x28, 0xca, 0x2f, 0xcb, 0x4c, 0x49,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x69, 0x5c, 0xc2, 0xee,
	0xc9, 0xc5, 0x8e, 0x50, 0x45, 0x01, 0x50, 0x35, 0x42, 0x12, 0x5c, 0xec, 0xa9, 0x79, 0x89, 0x49,
	0x39, 0xa9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x29, 0x17, 0x47,
	0x62, 0x72, 0x72, 0x7e, 0x69, 0x5e, 0x49, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x24,
	0xc4, 0x44, 0x3d, 0x24, 0x73, 0x1c, 0x21, 0x2a, 0x82, 0xe0, 0x4a, 0x95, 0x5c, 0xb8, 0x84, 0x30,
	0xe5, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0xc1, 0x76, 0x70, 0x06, 0x81, 0xd9, 0x42,
	0x52, 0x5c, 0x1c, 0x59, 0xc5, 0xf9, 0x79, 0x01, 0x89, 0x25, 0x19, 0x12, 0x4c, 0x60, 0x71, 0x38,
	0x3f, 0x89, 0x0d, 0x6c, 0x93, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x58, 0x30, 0x3f, 0xaf, 0xda,
	0x00, 0x00, 0x00,
}
