// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gitrepo_artifact_provider.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Git repo artifact provider.
type GitRepoArtifactProvider struct {
	// Whether the Git repo artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured Git Repo accounts.
	Accounts             []*GitRepoArtifactAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GitRepoArtifactProvider) Reset()         { *m = GitRepoArtifactProvider{} }
func (m *GitRepoArtifactProvider) String() string { return proto.CompactTextString(m) }
func (*GitRepoArtifactProvider) ProtoMessage()    {}
func (*GitRepoArtifactProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde915b29f1fac20, []int{0}
}

func (m *GitRepoArtifactProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitRepoArtifactProvider.Unmarshal(m, b)
}
func (m *GitRepoArtifactProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitRepoArtifactProvider.Marshal(b, m, deterministic)
}
func (m *GitRepoArtifactProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitRepoArtifactProvider.Merge(m, src)
}
func (m *GitRepoArtifactProvider) XXX_Size() int {
	return xxx_messageInfo_GitRepoArtifactProvider.Size(m)
}
func (m *GitRepoArtifactProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_GitRepoArtifactProvider.DiscardUnknown(m)
}

var xxx_messageInfo_GitRepoArtifactProvider proto.InternalMessageInfo

func (m *GitRepoArtifactProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *GitRepoArtifactProvider) GetAccounts() []*GitRepoArtifactAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for a Git repo artifact account. An account maps to a
// credential that is able to authenticate against a Git repository hosted by a
// Git hosting service. Either `username` and `password`,
// `usernamePasswordFile`, `token`, `tokenFile`, or `sshPrivateKeyFilePath` and
// `sshPrivateKeyPassphrase` must be set.
type GitRepoArtifactAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The username of the account.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// The password of the account.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// The path to a file containing the username and password of the account
	// in the format `${username}:${password}`.
	UsernamePasswordFile string `protobuf:"bytes,4,opt,name=usernamePasswordFile,proto3" json:"usernamePasswordFile,omitempty"`
	// The Git repo access token.
	Token string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	// The path to a file containing the Git repo access token.
	TokenFile string `protobuf:"bytes,6,opt,name=tokenFile,proto3" json:"tokenFile,omitempty"`
	// The path to an SSH private key to be used when connecting with the Git
	// repo over SSH.
	SshPrivateKeyFilePath string `protobuf:"bytes,7,opt,name=sshPrivateKeyFilePath,proto3" json:"sshPrivateKeyFilePath,omitempty"`
	// The passphrase to an SSH private key to be used when connecting with
	// the Git repo over SSH.
	SshPrivateKeyPassphrase string `protobuf:"bytes,8,opt,name=sshPrivateKeyPassphrase,proto3" json:"sshPrivateKeyPassphrase,omitempty"`
	// The path to a `known_hosts` file to be used when connecting with a
	// Git repository over SSH.
	SshKnownHostsFilePath string `protobuf:"bytes,9,opt,name=sshKnownHostsFilePath,proto3" json:"sshKnownHostsFilePath,omitempty"`
	// If `true`, Spinnaker can connect with a Git repository over SSH without
	// verifying the server's IP address against a `known_hosts` file.
	SshTrustUnknownHosts bool     `protobuf:"varint,10,opt,name=sshTrustUnknownHosts,proto3" json:"sshTrustUnknownHosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitRepoArtifactAccount) Reset()         { *m = GitRepoArtifactAccount{} }
func (m *GitRepoArtifactAccount) String() string { return proto.CompactTextString(m) }
func (*GitRepoArtifactAccount) ProtoMessage()    {}
func (*GitRepoArtifactAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde915b29f1fac20, []int{1}
}

func (m *GitRepoArtifactAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitRepoArtifactAccount.Unmarshal(m, b)
}
func (m *GitRepoArtifactAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitRepoArtifactAccount.Marshal(b, m, deterministic)
}
func (m *GitRepoArtifactAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitRepoArtifactAccount.Merge(m, src)
}
func (m *GitRepoArtifactAccount) XXX_Size() int {
	return xxx_messageInfo_GitRepoArtifactAccount.Size(m)
}
func (m *GitRepoArtifactAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_GitRepoArtifactAccount.DiscardUnknown(m)
}

var xxx_messageInfo_GitRepoArtifactAccount proto.InternalMessageInfo

func (m *GitRepoArtifactAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetUsernamePasswordFile() string {
	if m != nil {
		return m.UsernamePasswordFile
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetTokenFile() string {
	if m != nil {
		return m.TokenFile
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetSshPrivateKeyFilePath() string {
	if m != nil {
		return m.SshPrivateKeyFilePath
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetSshPrivateKeyPassphrase() string {
	if m != nil {
		return m.SshPrivateKeyPassphrase
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetSshKnownHostsFilePath() string {
	if m != nil {
		return m.SshKnownHostsFilePath
	}
	return ""
}

func (m *GitRepoArtifactAccount) GetSshTrustUnknownHosts() bool {
	if m != nil {
		return m.SshTrustUnknownHosts
	}
	return false
}

func init() {
	proto.RegisterType((*GitRepoArtifactProvider)(nil), "proto.GitRepoArtifactProvider")
	proto.RegisterType((*GitRepoArtifactAccount)(nil), "proto.GitRepoArtifactAccount")
}

func init() { proto.RegisterFile("gitrepo_artifact_provider.proto", fileDescriptor_bde915b29f1fac20) }

var fileDescriptor_bde915b29f1fac20 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xc7, 0xd9, 0xff, 0x2e, 0xbf, 0x5b, 0xd8, 0xcf, 0x05, 0x51, 0x1c, 0x03, 0x71, 0xa7, 0x15,
	0xa6, 0x07, 0x3d, 0xce, 0x83, 0x0a, 0xbb, 0x94, 0xa2, 0x17, 0x2f, 0x23, 0xeb, 0x1e, 0xd7, 0xd0,
	0x2e, 0x09, 0x49, 0xba, 0xe1, 0x1b, 0xf2, 0x75, 0x4a, 0x9f, 0xfe, 0x11, 0xb5, 0x9e, 0x9a, 0xe7,
	0xfb, 0xf9, 0x24, 0xdf, 0x92, 0x90, 0x8b, 0x9d, 0x70, 0x06, 0xb4, 0x5a, 0x73, 0xe3, 0xc4, 0x1b,
	0x8f, 0xdc, 0x5a, 0x1b, 0x75, 0x10, 0x5b, 0x30, 0x73, 0x6d, 0x94, 0x53, 0xb4, 0x87, 0x9f, 0xa9,
	0x24, 0xe3, 0x47, 0xe1, 0x42, 0xd0, 0x6a, 0x59, 0x8a, 0x41, 0xe9, 0x51, 0x46, 0x06, 0x20, 0xf9,
	0x26, 0x85, 0x2d, 0x6b, 0x4d, 0x5a, 0x33, 0x2f, 0xac, 0x46, 0x7a, 0x47, 0x3c, 0x1e, 0x45, 0x2a,
	0x93, 0xce, 0xb2, 0xf6, 0xa4, 0x33, 0xfb, 0xb7, 0x38, 0x2f, 0x4e, 0x9d, 0xff, 0x38, 0x6b, 0x59,
	0x58, 0x61, 0xad, 0x4f, 0x3f, 0x3a, 0xe4, 0xa4, 0x59, 0xa2, 0x94, 0x74, 0x25, 0xdf, 0x03, 0x96,
	0x0d, 0x43, 0x5c, 0xd3, 0x53, 0xe2, 0x65, 0x16, 0x0c, 0xe6, 0x6d, 0xcc, 0xeb, 0x39, 0x67, 0x9a,
	0x5b, 0x7b, 0x54, 0x66, 0xcb, 0x3a, 0x05, 0xab, 0x66, 0xba, 0x20, 0xa3, 0xca, 0x0b, 0xca, 0xec,
	0x41, 0xa4, 0xc0, 0xba, 0xe8, 0x35, 0x32, 0x3a, 0x22, 0x3d, 0xa7, 0x12, 0x90, 0xac, 0x87, 0x52,
	0x31, 0xd0, 0x33, 0x32, 0xc4, 0x05, 0x6e, 0xef, 0x23, 0xf9, 0x0a, 0xe8, 0x0d, 0xf9, 0x6f, 0x6d,
	0x1c, 0x18, 0x71, 0xe0, 0x0e, 0x56, 0xf0, 0x9e, 0x87, 0x01, 0x77, 0x31, 0x1b, 0xa0, 0xd9, 0x0c,
	0xe9, 0x2d, 0x19, 0x7f, 0x03, 0xf9, 0x6f, 0xe8, 0xd8, 0x70, 0x0b, 0xcc, 0xc3, 0x7d, 0x7f, 0xe1,
	0xb2, 0x6f, 0x25, 0xd5, 0x51, 0x3e, 0x29, 0xeb, 0x6c, 0xdd, 0x37, 0xac, 0xfb, 0x7e, 0xc3, 0xfc,
	0x36, 0xac, 0x8d, 0x9f, 0x4d, 0x66, 0xdd, 0x8b, 0x4c, 0x6a, 0xce, 0x08, 0x3e, 0x6b, 0x23, 0xbb,
	0xbf, 0x7a, 0xbd, 0xdc, 0x09, 0x17, 0x67, 0x9b, 0x79, 0xa4, 0xf6, 0xbe, 0xd5, 0x42, 0x4a, 0x9e,
	0x80, 0xf1, 0x93, 0x14, 0xb8, 0xf3, 0xb9, 0x16, 0x7e, 0x94, 0x0a, 0x90, 0x6e, 0xd3, 0xc7, 0x97,
	0xbf, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x28, 0xe8, 0xa3, 0xaf, 0x72, 0x02, 0x00, 0x00,
}
