// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the HTTP artifact provider.
type HttpProvider struct {
	// Whether the HTTP artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured HTTP accounts.
	Accounts             []*HttpAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HttpProvider) Reset()         { *m = HttpProvider{} }
func (m *HttpProvider) String() string { return proto.CompactTextString(m) }
func (*HttpProvider) ProtoMessage()    {}
func (*HttpProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{0}
}

func (m *HttpProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpProvider.Unmarshal(m, b)
}
func (m *HttpProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpProvider.Marshal(b, m, deterministic)
}
func (m *HttpProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpProvider.Merge(m, src)
}
func (m *HttpProvider) XXX_Size() int {
	return xxx_messageInfo_HttpProvider.Size(m)
}
func (m *HttpProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpProvider.DiscardUnknown(m)
}

var xxx_messageInfo_HttpProvider proto.InternalMessageInfo

func (m *HttpProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *HttpProvider) GetAccounts() []*HttpAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for an HTTP artifact account. Either `username` and `password`
// or `usernamePasswordFile` should be specified as means of authentication.
type HttpAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A username for HTTP basic auth.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// A password for HTTP basic auth.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// The path to a file containing the username and password for HTTP basic
	// auth. Must be in the format `${username}:${password}`.
	UsernamePasswordFile string   `protobuf:"bytes,4,opt,name=usernamePasswordFile,proto3" json:"usernamePasswordFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpAccount) Reset()         { *m = HttpAccount{} }
func (m *HttpAccount) String() string { return proto.CompactTextString(m) }
func (*HttpAccount) ProtoMessage()    {}
func (*HttpAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_11b04836674e6f94, []int{1}
}

func (m *HttpAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpAccount.Unmarshal(m, b)
}
func (m *HttpAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpAccount.Marshal(b, m, deterministic)
}
func (m *HttpAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpAccount.Merge(m, src)
}
func (m *HttpAccount) XXX_Size() int {
	return xxx_messageInfo_HttpAccount.Size(m)
}
func (m *HttpAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpAccount.DiscardUnknown(m)
}

var xxx_messageInfo_HttpAccount proto.InternalMessageInfo

func (m *HttpAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HttpAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *HttpAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *HttpAccount) GetUsernamePasswordFile() string {
	if m != nil {
		return m.UsernamePasswordFile
	}
	return ""
}

func init() {
	proto.RegisterType((*HttpProvider)(nil), "proto.HttpProvider")
	proto.RegisterType((*HttpAccount)(nil), "proto.HttpAccount")
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_11b04836674e6f94) }

var fileDescriptor_11b04836674e6f94 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x28, 0x29, 0x29,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x11, 0x5c, 0x3c, 0x1e, 0x25,
	0x25, 0x05, 0x01, 0x45, 0xf9, 0x65, 0x99, 0x29, 0xa9, 0x45, 0x42, 0x12, 0x5c, 0xec, 0xa9, 0x79,
	0x89, 0x49, 0x39, 0xa9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x1e,
	0x17, 0x47, 0x62, 0x72, 0x72, 0x7e, 0x69, 0x5e, 0x49, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7,
	0x91, 0x10, 0xc4, 0x28, 0x3d, 0x90, 0x01, 0x8e, 0x10, 0xa9, 0x20, 0xb8, 0x1a, 0xa5, 0x5e, 0x46,
	0x2e, 0x6e, 0x24, 0x19, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0xb0, 0xb1, 0x9c, 0x41,
	0x60, 0xb6, 0x90, 0x14, 0x17, 0x47, 0x69, 0x71, 0x6a, 0x11, 0x58, 0x9c, 0x09, 0x2c, 0x0e, 0xe7,
	0x83, 0xe4, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0x21, 0x72, 0x30, 0xbe,
	0x90, 0x11, 0x97, 0x08, 0x4c, 0x5d, 0x00, 0x54, 0xcc, 0x2d, 0x33, 0x27, 0x55, 0x82, 0x05, 0xac,
	0x0e, 0xab, 0x5c, 0x12, 0x1b, 0xd8, 0xb1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xfe,
	0x96, 0xc4, 0x05, 0x01, 0x00, 0x00,
}
