// Code generated by protoc-gen-go. DO NOT EDIT.
// source: maven.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Maven artifact provider.
type MavenProvider struct {
	// Whether the Maven artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured Maven accounts.
	Accounts             []*MavenAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MavenProvider) Reset()         { *m = MavenProvider{} }
func (m *MavenProvider) String() string { return proto.CompactTextString(m) }
func (*MavenProvider) ProtoMessage()    {}
func (*MavenProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0aef1f9f58b17a2, []int{0}
}

func (m *MavenProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenProvider.Unmarshal(m, b)
}
func (m *MavenProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenProvider.Marshal(b, m, deterministic)
}
func (m *MavenProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenProvider.Merge(m, src)
}
func (m *MavenProvider) XXX_Size() int {
	return xxx_messageInfo_MavenProvider.Size(m)
}
func (m *MavenProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenProvider.DiscardUnknown(m)
}

var xxx_messageInfo_MavenProvider proto.InternalMessageInfo

func (m *MavenProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *MavenProvider) GetAccounts() []*MavenAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for a Maven artifact account.
type MavenAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// (Required) Full URI for the Maven repository (e.g.,
	// `http://some.host.com/repository/path`).
	RepositoryUrl        string   `protobuf:"bytes,2,opt,name=repositoryUrl,proto3" json:"repositoryUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MavenAccount) Reset()         { *m = MavenAccount{} }
func (m *MavenAccount) String() string { return proto.CompactTextString(m) }
func (*MavenAccount) ProtoMessage()    {}
func (*MavenAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0aef1f9f58b17a2, []int{1}
}

func (m *MavenAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MavenAccount.Unmarshal(m, b)
}
func (m *MavenAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MavenAccount.Marshal(b, m, deterministic)
}
func (m *MavenAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MavenAccount.Merge(m, src)
}
func (m *MavenAccount) XXX_Size() int {
	return xxx_messageInfo_MavenAccount.Size(m)
}
func (m *MavenAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MavenAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MavenAccount proto.InternalMessageInfo

func (m *MavenAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MavenAccount) GetRepositoryUrl() string {
	if m != nil {
		return m.RepositoryUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*MavenProvider)(nil), "proto.MavenProvider")
	proto.RegisterType((*MavenAccount)(nil), "proto.MavenAccount")
}

func init() { proto.RegisterFile("maven.proto", fileDescriptor_b0aef1f9f58b17a2) }

var fileDescriptor_b0aef1f9f58b17a2 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4d, 0x2c, 0x4b,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x51, 0x5c, 0xbc, 0xbe,
	0x20, 0xd1, 0x80, 0xa2, 0xfc, 0xb2, 0xcc, 0x94, 0xd4, 0x22, 0x21, 0x09, 0x2e, 0xf6, 0xd4, 0xbc,
	0xc4, 0xa4, 0x9c, 0xd4, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x18, 0x57, 0x48, 0x9f,
	0x8b, 0x23, 0x31, 0x39, 0x39, 0xbf, 0x34, 0xaf, 0xa4, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb,
	0x48, 0x18, 0x62, 0x96, 0x1e, 0xd8, 0x04, 0x47, 0x88, 0x5c, 0x10, 0x5c, 0x91, 0x92, 0x07, 0x17,
	0x0f, 0xb2, 0x8c, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0x2a, 0xd8, 0x5c, 0xce, 0x20, 0x30,
	0x5b, 0x48, 0x85, 0x8b, 0xb7, 0x28, 0xb5, 0x20, 0xbf, 0x38, 0xb3, 0x24, 0xbf, 0xa8, 0x32, 0xb4,
	0x28, 0x47, 0x82, 0x09, 0x2c, 0x89, 0x2a, 0x98, 0xc4, 0x06, 0xb6, 0xc7, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x39, 0xb9, 0xe2, 0xcf, 0xc2, 0x00, 0x00, 0x00,
}
