// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oracle_artifact.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the Oracle artifact provider.
type OracleArtifactProvider struct {
	// Whether the Oracle artifact provider is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The list of configured Oracle artifact accounts.
	Accounts             []*OracleArtifactAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OracleArtifactProvider) Reset()         { *m = OracleArtifactProvider{} }
func (m *OracleArtifactProvider) String() string { return proto.CompactTextString(m) }
func (*OracleArtifactProvider) ProtoMessage()    {}
func (*OracleArtifactProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cd1d81fe81e6552, []int{0}
}

func (m *OracleArtifactProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OracleArtifactProvider.Unmarshal(m, b)
}
func (m *OracleArtifactProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OracleArtifactProvider.Marshal(b, m, deterministic)
}
func (m *OracleArtifactProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleArtifactProvider.Merge(m, src)
}
func (m *OracleArtifactProvider) XXX_Size() int {
	return xxx_messageInfo_OracleArtifactProvider.Size(m)
}
func (m *OracleArtifactProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleArtifactProvider.DiscardUnknown(m)
}

var xxx_messageInfo_OracleArtifactProvider proto.InternalMessageInfo

func (m *OracleArtifactProvider) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *OracleArtifactProvider) GetAccounts() []*OracleArtifactAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Configuration for an Oracle artifact account.
type OracleArtifactAccount struct {
	// The name of the account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The fingerprint of the public key.
	Fingerprint string `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// The namespace in which the bucket and objects should be created.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The passphrase used for the private key, if it is encrypted.
	PrivateKeyPassphrase string `protobuf:"bytes,4,opt,name=privateKeyPassphrase,proto3" json:"privateKeyPassphrase,omitempty"`
	// An Oracle region (e.g., `us-phoenix-1`).
	Region string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	// Path to the private key in PEM format.
	SshPrivateKeyFilePath string `protobuf:"bytes,6,opt,name=sshPrivateKeyFilePath,proto3" json:"sshPrivateKeyFilePath,omitempty"`
	// The OCID of the Oracle Tenancy to use.
	TenancyId string `protobuf:"bytes,7,opt,name=tenancyId,proto3" json:"tenancyId,omitempty"`
	// The OCID of the Oracle User with which to authenticate.
	UserId               string   `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OracleArtifactAccount) Reset()         { *m = OracleArtifactAccount{} }
func (m *OracleArtifactAccount) String() string { return proto.CompactTextString(m) }
func (*OracleArtifactAccount) ProtoMessage()    {}
func (*OracleArtifactAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cd1d81fe81e6552, []int{1}
}

func (m *OracleArtifactAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OracleArtifactAccount.Unmarshal(m, b)
}
func (m *OracleArtifactAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OracleArtifactAccount.Marshal(b, m, deterministic)
}
func (m *OracleArtifactAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleArtifactAccount.Merge(m, src)
}
func (m *OracleArtifactAccount) XXX_Size() int {
	return xxx_messageInfo_OracleArtifactAccount.Size(m)
}
func (m *OracleArtifactAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleArtifactAccount.DiscardUnknown(m)
}

var xxx_messageInfo_OracleArtifactAccount proto.InternalMessageInfo

func (m *OracleArtifactAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OracleArtifactAccount) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *OracleArtifactAccount) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *OracleArtifactAccount) GetPrivateKeyPassphrase() string {
	if m != nil {
		return m.PrivateKeyPassphrase
	}
	return ""
}

func (m *OracleArtifactAccount) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *OracleArtifactAccount) GetSshPrivateKeyFilePath() string {
	if m != nil {
		return m.SshPrivateKeyFilePath
	}
	return ""
}

func (m *OracleArtifactAccount) GetTenancyId() string {
	if m != nil {
		return m.TenancyId
	}
	return ""
}

func (m *OracleArtifactAccount) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*OracleArtifactProvider)(nil), "proto.OracleArtifactProvider")
	proto.RegisterType((*OracleArtifactAccount)(nil), "proto.OracleArtifactAccount")
}

func init() { proto.RegisterFile("oracle_artifact.proto", fileDescriptor_7cd1d81fe81e6552) }

var fileDescriptor_7cd1d81fe81e6552 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x6e, 0xc2, 0x30,
	0x10, 0x86, 0x45, 0x80, 0x10, 0x8e, 0xcd, 0x6a, 0x90, 0x07, 0x86, 0x88, 0x89, 0x89, 0x81, 0x76,
	0xe8, 0xca, 0x52, 0x09, 0x75, 0x68, 0x94, 0x17, 0xa8, 0x0e, 0xe7, 0x20, 0x96, 0x52, 0x3b, 0x3a,
	0x1b, 0x24, 0x9e, 0xa7, 0x2f, 0x5a, 0xc5, 0xa1, 0x69, 0x91, 0x32, 0xd9, 0x77, 0xdf, 0xe7, 0xfb,
	0x4f, 0x86, 0xd4, 0x32, 0xaa, 0x9a, 0x3e, 0x91, 0xbd, 0x3e, 0xa1, 0xf2, 0xdb, 0x86, 0xad, 0xb7,
	0x62, 0x1a, 0x8e, 0x75, 0x0d, 0xcb, 0x8f, 0xc0, 0xf7, 0x77, 0x9c, 0xb3, 0xbd, 0xea, 0x92, 0x58,
	0x48, 0x98, 0x91, 0xc1, 0x63, 0x4d, 0xa5, 0x1c, 0x65, 0xa3, 0x4d, 0x52, 0xfc, 0x96, 0xe2, 0x15,
	0x12, 0x54, 0xca, 0x5e, 0x8c, 0x77, 0x32, 0xca, 0xc6, 0x9b, 0xc5, 0x6e, 0xd5, 0x0d, 0xdd, 0x3e,
	0x8e, 0xda, 0x77, 0x52, 0xd1, 0xdb, 0xeb, 0xef, 0x08, 0xd2, 0x41, 0x47, 0x08, 0x98, 0x18, 0xfc,
	0xa2, 0x10, 0x35, 0x2f, 0xc2, 0x5d, 0x64, 0xb0, 0x38, 0x69, 0x73, 0x26, 0x6e, 0x58, 0x1b, 0x2f,
	0xa3, 0x80, 0xfe, 0xb7, 0xc4, 0x0a, 0xe6, 0xad, 0xe9, 0x1a, 0x54, 0x24, 0xc7, 0x81, 0xff, 0x35,
	0xc4, 0x0e, 0x9e, 0x1a, 0xd6, 0x57, 0xf4, 0xf4, 0x4e, 0xb7, 0x1c, 0x9d, 0x6b, 0x2a, 0x46, 0x47,
	0x72, 0x12, 0xc4, 0x41, 0x26, 0x96, 0x10, 0x33, 0x9d, 0xb5, 0x35, 0x72, 0x1a, 0xac, 0x7b, 0x25,
	0x5e, 0x20, 0x75, 0xae, 0xca, 0xfb, 0x27, 0x6f, 0xba, 0xa6, 0x1c, 0x7d, 0x25, 0xe3, 0xa0, 0x0d,
	0xc3, 0x76, 0x3f, 0x4f, 0x06, 0x8d, 0xba, 0x1d, 0x4a, 0x39, 0xeb, 0xf6, 0xeb, 0x1b, 0x6d, 0xd6,
	0xc5, 0x11, 0x1f, 0x4a, 0x99, 0x74, 0x59, 0x5d, 0x75, 0x8c, 0xc3, 0x67, 0x3e, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x32, 0xa3, 0x81, 0x13, 0xba, 0x01, 0x00, 0x00,
}
