// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: permissions.proto

package client

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// A Fiat permissions configuration object.
type Permissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A user must have at least one of these roles in order to view this
	// account's cloud resources.
	READ []string `protobuf:"bytes,1,rep,name=READ,proto3" json:"READ,omitempty"`
	// A user must have at least one of these roles in order to make changes to
	// this account's cloud resources.
	WRITE []string `protobuf:"bytes,2,rep,name=WRITE,proto3" json:"WRITE,omitempty"`
	// A user must have at least one of these roles in order to execute
	// pipelines.
	EXECUTE []string `protobuf:"bytes,3,rep,name=EXECUTE,proto3" json:"EXECUTE,omitempty"`
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permissions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *Permissions) GetREAD() []string {
	if x != nil {
		return x.READ
	}
	return nil
}

func (x *Permissions) GetWRITE() []string {
	if x != nil {
		return x.WRITE
	}
	return nil
}

func (x *Permissions) GetEXECUTE() []string {
	if x != nil {
		return x.EXECUTE
	}
	return nil
}

var File_permissions_proto protoreflect.FileDescriptor

var file_permissions_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x0b, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x45, 0x41,
	0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x52, 0x45, 0x41, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x57, 0x52, 0x49, 0x54, 0x45, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x57, 0x52,
	0x49, 0x54, 0x45, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x69, 0x6e,
	0x6e, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x6b, 0x6c, 0x65, 0x61, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_permissions_proto_rawDescOnce sync.Once
	file_permissions_proto_rawDescData = file_permissions_proto_rawDesc
)

func file_permissions_proto_rawDescGZIP() []byte {
	file_permissions_proto_rawDescOnce.Do(func() {
		file_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(file_permissions_proto_rawDescData)
	})
	return file_permissions_proto_rawDescData
}

var file_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_permissions_proto_goTypes = []interface{}{
	(*Permissions)(nil), // 0: proto.Permissions
}
var file_permissions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permissions_proto_init() }
func file_permissions_proto_init() {
	if File_permissions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_permissions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_permissions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permissions_proto_goTypes,
		DependencyIndexes: file_permissions_proto_depIdxs,
		MessageInfos:      file_permissions_proto_msgTypes,
	}.Build()
	File_permissions_proto = out.File
	file_permissions_proto_rawDesc = nil
	file_permissions_proto_goTypes = nil
	file_permissions_proto_depIdxs = nil
}
