// Code generated by protoc-gen-go. DO NOT EDIT.
// source: halconfig.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HalConfig struct {
	PersistentStorage    *HalConfig_PersistentStorage `protobuf:"bytes,1,opt,name=persistentStorage,proto3" json:"persistentStorage,omitempty"`
	Providers            *HalConfig_Providers         `protobuf:"bytes,2,opt,name=providers,proto3" json:"providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *HalConfig) Reset()         { *m = HalConfig{} }
func (m *HalConfig) String() string { return proto.CompactTextString(m) }
func (*HalConfig) ProtoMessage()    {}
func (*HalConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_cda1892e07435feb, []int{0}
}

func (m *HalConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HalConfig.Unmarshal(m, b)
}
func (m *HalConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HalConfig.Marshal(b, m, deterministic)
}
func (m *HalConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HalConfig.Merge(m, src)
}
func (m *HalConfig) XXX_Size() int {
	return xxx_messageInfo_HalConfig.Size(m)
}
func (m *HalConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HalConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HalConfig proto.InternalMessageInfo

func (m *HalConfig) GetPersistentStorage() *HalConfig_PersistentStorage {
	if m != nil {
		return m.PersistentStorage
	}
	return nil
}

func (m *HalConfig) GetProviders() *HalConfig_Providers {
	if m != nil {
		return m.Providers
	}
	return nil
}

type HalConfig_PersistentStorage struct {
	PersistentStoreType  string   `protobuf:"bytes,1,opt,name=persistentStoreType,proto3" json:"persistentStoreType,omitempty"`
	Gcs                  *GCS     `protobuf:"bytes,2,opt,name=gcs,proto3" json:"gcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HalConfig_PersistentStorage) Reset()         { *m = HalConfig_PersistentStorage{} }
func (m *HalConfig_PersistentStorage) String() string { return proto.CompactTextString(m) }
func (*HalConfig_PersistentStorage) ProtoMessage()    {}
func (*HalConfig_PersistentStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cda1892e07435feb, []int{0, 0}
}

func (m *HalConfig_PersistentStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HalConfig_PersistentStorage.Unmarshal(m, b)
}
func (m *HalConfig_PersistentStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HalConfig_PersistentStorage.Marshal(b, m, deterministic)
}
func (m *HalConfig_PersistentStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HalConfig_PersistentStorage.Merge(m, src)
}
func (m *HalConfig_PersistentStorage) XXX_Size() int {
	return xxx_messageInfo_HalConfig_PersistentStorage.Size(m)
}
func (m *HalConfig_PersistentStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_HalConfig_PersistentStorage.DiscardUnknown(m)
}

var xxx_messageInfo_HalConfig_PersistentStorage proto.InternalMessageInfo

func (m *HalConfig_PersistentStorage) GetPersistentStoreType() string {
	if m != nil {
		return m.PersistentStoreType
	}
	return ""
}

func (m *HalConfig_PersistentStorage) GetGcs() *GCS {
	if m != nil {
		return m.Gcs
	}
	return nil
}

type HalConfig_Providers struct {
	Kubernetes           *Kubernetes `protobuf:"bytes,1,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	Google               *Google     `protobuf:"bytes,2,opt,name=google,proto3" json:"google,omitempty"`
	Appengine            *Appengine  `protobuf:"bytes,3,opt,name=appengine,proto3" json:"appengine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HalConfig_Providers) Reset()         { *m = HalConfig_Providers{} }
func (m *HalConfig_Providers) String() string { return proto.CompactTextString(m) }
func (*HalConfig_Providers) ProtoMessage()    {}
func (*HalConfig_Providers) Descriptor() ([]byte, []int) {
	return fileDescriptor_cda1892e07435feb, []int{0, 1}
}

func (m *HalConfig_Providers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HalConfig_Providers.Unmarshal(m, b)
}
func (m *HalConfig_Providers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HalConfig_Providers.Marshal(b, m, deterministic)
}
func (m *HalConfig_Providers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HalConfig_Providers.Merge(m, src)
}
func (m *HalConfig_Providers) XXX_Size() int {
	return xxx_messageInfo_HalConfig_Providers.Size(m)
}
func (m *HalConfig_Providers) XXX_DiscardUnknown() {
	xxx_messageInfo_HalConfig_Providers.DiscardUnknown(m)
}

var xxx_messageInfo_HalConfig_Providers proto.InternalMessageInfo

func (m *HalConfig_Providers) GetKubernetes() *Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

func (m *HalConfig_Providers) GetGoogle() *Google {
	if m != nil {
		return m.Google
	}
	return nil
}

func (m *HalConfig_Providers) GetAppengine() *Appengine {
	if m != nil {
		return m.Appengine
	}
	return nil
}

func init() {
	proto.RegisterType((*HalConfig)(nil), "proto.HalConfig")
	proto.RegisterType((*HalConfig_PersistentStorage)(nil), "proto.HalConfig.PersistentStorage")
	proto.RegisterType((*HalConfig_Providers)(nil), "proto.HalConfig.Providers")
}

func init() { proto.RegisterFile("halconfig.proto", fileDescriptor_cda1892e07435feb) }

var fileDescriptor_cda1892e07435feb = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0xa9, 0xc5, 0x81, 0x5c, 0x91, 0xb1, 0xd7, 0x85, 0x25, 0xb8, 0x90, 0x01, 0xc1, 0x55,
	0xf1, 0x67, 0xe3, 0x56, 0x66, 0xa1, 0xe0, 0x66, 0xc8, 0xf8, 0x02, 0x6d, 0xbd, 0xc6, 0x62, 0x49,
	0x42, 0x12, 0x05, 0xdf, 0x43, 0xdf, 0x57, 0x4c, 0xd2, 0x56, 0xad, 0xab, 0xc2, 0x39, 0xdf, 0xb9,
	0x5f, 0x03, 0xcb, 0xe7, 0xba, 0x6f, 0xb5, 0x7a, 0xea, 0x64, 0x65, 0xac, 0xf6, 0x1a, 0x77, 0xc3,
	0x87, 0x1f, 0x19, 0xb2, 0xae, 0x73, 0x9e, 0x94, 0x77, 0x5e, 0xdb, 0x5a, 0x52, 0xec, 0xf9, 0xd2,
	0x58, 0xfd, 0xd6, 0x3d, 0x92, 0x75, 0x31, 0x58, 0x7d, 0xe4, 0xc0, 0xee, 0xea, 0x7e, 0x1d, 0x8e,
	0xe0, 0x06, 0x8a, 0x69, 0xb9, 0x8d, 0xcb, 0x32, 0x3b, 0xc9, 0xce, 0xf6, 0x2e, 0x57, 0x71, 0x50,
	0x8d, 0x70, 0xb5, 0xf9, 0x4b, 0x8a, 0xf9, 0x18, 0xaf, 0x81, 0x8d, 0xca, 0x72, 0x27, 0x5c, 0xe2,
	0xf3, 0x4b, 0x03, 0x21, 0x26, 0x98, 0xb7, 0x50, 0xcc, 0x0c, 0x78, 0x0e, 0x87, 0xbf, 0x1d, 0xf4,
	0xf0, 0x6e, 0xe2, 0x2f, 0x32, 0xf1, 0x5f, 0x85, 0xc7, 0x90, 0xcb, 0x76, 0x50, 0x43, 0x52, 0xdf,
	0xae, 0xb7, 0xe2, 0x3b, 0xe6, 0x9f, 0x19, 0xb0, 0xd1, 0x8e, 0x17, 0x00, 0x2f, 0xaf, 0x0d, 0x59,
	0x45, 0x9e, 0x5c, 0x7a, 0x77, 0x91, 0x26, 0xf7, 0x63, 0x21, 0x7e, 0x40, 0x78, 0x0a, 0x0b, 0xa9,
	0xb5, 0xec, 0x29, 0x19, 0xf6, 0x07, 0x43, 0x08, 0x45, 0x2a, 0xb1, 0x02, 0x56, 0x1b, 0x43, 0x4a,
	0x76, 0x8a, 0xca, 0x3c, 0x90, 0x07, 0x89, 0xbc, 0x19, 0x72, 0x31, 0x21, 0xcd, 0x22, 0x74, 0x57,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0x4b, 0xb9, 0x74, 0xe1, 0x01, 0x00, 0x00,
}
