// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: canary/supported_type.proto

package canary

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SupportedType int32

const (
	// Unspecified. Do not directly use, instead omit the field.
	SupportedType_UNSPECIFIED         SupportedType = 0
	SupportedType_METRICS_STORE       SupportedType = 1
	SupportedType_CONFIGURATION_STORE SupportedType = 2
	SupportedType_OBJECT_STORE        SupportedType = 3
)

// Enum value maps for SupportedType.
var (
	SupportedType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "METRICS_STORE",
		2: "CONFIGURATION_STORE",
		3: "OBJECT_STORE",
	}
	SupportedType_value = map[string]int32{
		"UNSPECIFIED":         0,
		"METRICS_STORE":       1,
		"CONFIGURATION_STORE": 2,
		"OBJECT_STORE":        3,
	}
)

func (x SupportedType) Enum() *SupportedType {
	p := new(SupportedType)
	*p = x
	return p
}

func (x SupportedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupportedType) Descriptor() protoreflect.EnumDescriptor {
	return file_canary_supported_type_proto_enumTypes[0].Descriptor()
}

func (SupportedType) Type() protoreflect.EnumType {
	return &file_canary_supported_type_proto_enumTypes[0]
}

func (x SupportedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupportedType.Descriptor instead.
func (SupportedType) EnumDescriptor() ([]byte, []int) {
	return file_canary_supported_type_proto_rawDescGZIP(), []int{0}
}

var File_canary_supported_type_proto protoreflect.FileDescriptor

var file_canary_supported_type_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x61, 0x6e, 0x61, 0x72, 0x79, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x61, 0x6e, 0x61, 0x72, 0x79, 0x2a, 0x5e, 0x0a, 0x0d, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43, 0x53, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x42, 0x4a,
	0x45, 0x43, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x10, 0x03, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x69, 0x6e, 0x6e, 0x61,
	0x6b, 0x65, 0x72, 0x2f, 0x6b, 0x6c, 0x65, 0x61, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x61, 0x6e, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_canary_supported_type_proto_rawDescOnce sync.Once
	file_canary_supported_type_proto_rawDescData = file_canary_supported_type_proto_rawDesc
)

func file_canary_supported_type_proto_rawDescGZIP() []byte {
	file_canary_supported_type_proto_rawDescOnce.Do(func() {
		file_canary_supported_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_canary_supported_type_proto_rawDescData)
	})
	return file_canary_supported_type_proto_rawDescData
}

var file_canary_supported_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_canary_supported_type_proto_goTypes = []interface{}{
	(SupportedType)(0), // 0: proto.canary.SupportedType
}
var file_canary_supported_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_canary_supported_type_proto_init() }
func file_canary_supported_type_proto_init() {
	if File_canary_supported_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_canary_supported_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_canary_supported_type_proto_goTypes,
		DependencyIndexes: file_canary_supported_type_proto_depIdxs,
		EnumInfos:         file_canary_supported_type_proto_enumTypes,
	}.Build()
	File_canary_supported_type_proto = out.File
	file_canary_supported_type_proto_rawDesc = nil
	file_canary_supported_type_proto_goTypes = nil
	file_canary_supported_type_proto_depIdxs = nil
}
